@startuml Massage Use Case DiagramBorderColor
' left to right direction
skinparam Linetype ortho
skinparam actor{
    borderthickness = 3
}

actor "Customer" as customer
actor "Admin" as admin
actor "Guest" as guest

folder "Authentication System" as Asystem{
    usecase "Register" as Reg
    usecase "Login" as login
    usecase "Logout" as logout
}
folder "Massage Shop Sytem" as Shop{
    usecase "View All Shops" as viewShopLists
    usecase "Manage Shop" as manageshop
}
folder "Reservation System" as Rsystem{
    usecase "View Reservations" as viewReservations
    usecase "Manage Reservation" as manageReservation
}

guest -- login
guest -- Reg
guest -- viewShopLists

customer -- login  
customer -- logout
customer -- viewShopLists
customer -- viewReservations
customer -- manageReservation

login -- admin
logout -- admin
manageshop -- admin
viewShopLists -- admin
viewReservations -- admin
manageReservation -- admin

@enduml