@startuml Manage Shop (POST)


footer Page %page% of %lastpage%
title "Manage Shop (POST)"

participant "Client" as client
participant "<<JavaScript>>\n:server" as server
participant "<<router>>\n:shops" as routerShops
participant "<<controllers>>\n:shops" as controllersShops
participant "<<model>>\n:Shop" as modelShop
database "<<MongoDB>>\n:shops" as ShopsDatabase

client -> server ++ : req.post('/api/v1/shops')
server -> routerShops ++ : app.use('/api/v1/shops', shops)
routerShops -> controllersShops ++ : createShop
controllersShops -> modelShop ++ : create(req.body)
modelShop -> ShopsDatabase ++ : ShopSchema

ShopsDatabase --> modelShop -- : shop
modelShop -> controllersShops -- : shop
controllersShops --> client -- : response (shop)

@enduml
