@startuml "Manage Authentication (PUT)"

title "User Login (GET /api/v1/auth/login)"
participant "Client" as client
participant "<<JavaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuth
participant "<<models>>\n:User (Mongoose)" as modelUser
database "<<MongoDB>>\n:users" as UsersDatabase

client -> server : POST /api/v1/auth/login
server -> routerAuth : app.use('/api/v1/auth', auth)
routerAuth -> controllersAuth : login

controllersAuth -> modelUser : findOne({ email }).select('+password')
modelUser -> UsersDatabase : findOne({ email })
UsersDatabase --> modelUser : Return user document

controllersAuth -> modelUser : user.matchPassword(password)
modelUser --> controllersAuth : Return true/false

controllersAuth -> controllersAuth : sendTokenResponse(user, 200, res)
controllersAuth -> client : JSON { succes, token }

@enduml
